### ISSUE TITLE
Cannot reach clu.informatik.uni-freiburg.de

### ISSUE THREAD

**Issue by matterda** [voelkerb/FIRED_dataset_helper#3]
I have been trying for the past few days to get the data, but `rsync` cannot reach `clu.informatik.uni-freiburg.de`:
```console
$ rsync -avzh --progress rsync://FIRED@clu.informatik.uni-freiburg.de/FIRED/ /home/me/FIRED/
rsync: failed to connect to clu.informatik.uni-freiburg.de (132.230.150.87): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
```

**Comment by voelkerb** [comment]
Hey Matterda, 

I am aware of the problem since last friday. It's only a temporary problem due to a firewall added by our sys admin. We will sort this out in the following days/hours. Meanwhile you can access the 1Hz data under this [Nextcloud Link](https://nextcloud.voelkerb.com/s/CFqjj3jqZyDi8Z6).
Sorry for your trouble!
Ben

**Comment by matterda** [comment]
Hi Ben,
Thanks a lot for the link! I think Nextcloud's password is different from the one provided in the `README.md` file. If you cannot share it, it's OK: I will try through rsync again in the next few days.
Mattia

**Comment by voelkerb** [comment]
ah yes sorry for that, it is "fired"

**Comment by voelkerb** [comment]
Rsync connection issue is fixed - thanks for reporting! I will close the issue.
